In [151]:
import pandas as pd
import re
import numpy as np

# MENTIONS

In [159]:
tweet = pd.read_csv("C:/Users/Angela/Desktop/SARDINE/dataset/df_finale_true_cluster.csv")

In [9]:
#eliminazione mentions dal testo (@...), url e emoji (<..>)
def remove_mentions(x):
    p = re.sub(r'@([^\s:]+)','', x)
    return p

def remove_url(x):
    p = re.sub(r'http\S+','', x)
    return p

def remove_emoji(x):
    p = re.sub(r'(\<u+\S*\>)', '',x)
    return p tweet["text_def"] = tweet["text"].apply(remove_mentions)

In [10]:
tweet["text_def"] = tweet["text_def"].apply(remove_url)
tweet["text_def"]= tweet["text_def"].replace("\n", "", regex = True)
tweet["text_def"] = tweet["text_def"].replace("#", "", regex = True)
tweet["text_def"] = tweet["text_def"].replace("-", "", regex = True)
tweet["text_def"] = tweet["text_def"].replace("_", "", regex = True)
tweet["text_def"] = tweet["text_def"].replace(",", "", regex = True)
tweet["text_def"] = tweet["text_def"].replace(":", "", regex = True)
tweet["text_def"] = tweet["text_def"].replace(";", "", regex = True)
tweet["text_def"] = tweet["text_def"].replace("\"", "", regex = True)
tweet["text_def"] = tweet["text_def"].replace("\'", "", regex = True)
tweet["text_def"] = tweet["text_def"].replace("=", "", regex = True)
tweet["text_def"] = tweet["text_def"].replace("\?", "", regex = True)
tweet["text_def"] = tweet["text_def"].replace("!", "", regex = True)
tweet["text_def"] = tweet["text_def"].replace("\.", " ", regex = True)
tweet["text_def"] = tweet["text_def"].replace("\(", "", regex = True)
tweet["text_def"] = tweet["text_def"].replace("\)", "", regex = True)
tweet["text_def"] = tweet["text_def"].replace("\“", "", regex = True)
tweet["text_def"] = tweet["text_def"].replace("\s+", " ", regex = True)
tweet["text_def"] = tweet["text_def"].replace("\d*", "", regex = True)
tweet["text_def"] = tweet["text_def"].replace("RT", "", regex = True)
tweet["text_def"] = tweet["text_def"].str.lower()
tweet["text_def"] = tweet["text_def"].apply(remove_emoji)

In [127]:
tweet["text_def"]

0        scherzetto di che domanda alle sardine cosa ne...
1        le famose piazze delle sardine contro l’odio a...
2        la confusione de sto ragazzo è palese e lampan...
3        mattia santori scende in piazza per bonaccini ...
4        se la gente partecipa nelle piazze va bene ma ...
5        ma chi glielo dice a questa sardina che al gov...
6        io ho solo una domanda ma esigo una risposta m...
7        tutti questi complimenti da parte del pd e di ...
8        dimaio dobbiamo lavorare per i prossimi  anni ...
9         vi danno pure troppo spago sardine pagate con...
10        il coglione è lideatore e il finanziatore del...
11       salvini sardine chiedono che un ministro non p...
12       di maio «nazionalizzare la popolare di bari be...
13       gassman con le sardinechi gassman quello che d...
14       in piazza a roma la morte dellintelligenza amm...
15       il leader delle sardine gli elettori della leg...
16       il leader delle sardine siamo evidentemente vi...
17       matteo salvini durissimo con mattia santori le...
18         manifestazioni in tutto il paese milioni di ...
19       i papaboys di bergoglio benedicono le sardines...
20       altra mini inchiesta di che stavolta chiede al...
21       prima il ciuccio poi lulivo e adesso i pdioti ...
22       quindi bonaccini dice che non è del pd giusepp...
23       il mes è anti costituzionale ci sarà questo ti...
24       endorsement di orlando alle sardine  chiedono ...
25       rizzo non cè nulla di più organizzato di un mo...
26       casapound fa un tweet le sardine abboccano e v...
27       rizzo ha appena dato dei fascisti alle sardine...
28       conte al corriere siamo pronti per la maratona...
29       manca solo la delegazione di confindustria la ...
                               ...
37994    oggi tutti i non sardine possono solo stare in...
37995    sardine oggi in piazza san giovanni la prova d...
37996    avete presente il concetto di mareaeccolo quir...
37997    sardinecontrosalvini sardine la volete una taz...
37998    tante sardine ma proprio tante tante i giovani...
37999    si può andare in piazza senza odiare e senza r...
38000                            non sei ito dalle sardine
38001    francia le proteste per la libertà dalla ditta...
38002    situazione le sardine tolgono voti alla lega l...
38003    sardine a roma in migliaia a san giovanni anpi...
38004    un sogno si è avverato non possiamo non dobbia...
38005     unaltra che sta nel movimento per distruggerl...
38006    laltro giorno ho visto una serie di immagini m...
38007    sardine a roma linno spontaneo della piazza tu...
38008    questi ragazzi hanno riattivato una speranza u...
38009     il punto  delle proposte lanciate dalle sardi...
38010    e alla fine eccoci qui in questa piazza incred...
38011    eravamo in depressione perché le piazze si rie...
38012                                      che spettacolo
38013    piazza san giovanni strapiena non è servito in...
38014    grazie per aver reso roma così bella per la pa...
38015    le sardine hanno ottenuto un risultato politic...
38016     li inglesi gle sardine se gle mangiano ha col...
38017                                      che spettacolo
38018     vale ma hai visto i pesci pene che si sono sp...
38019     gentile renzi il movimento sardine non è un p...
38020    santoro ha costruito con la complicità della m...
38021    brexit nessuno dice che la sterlina e la borsa...
38022    avete presente il concetto di mareaeccolo quir...
38023    sardinecontrosalvini sardine la volete una taz...
Name: text_def, Length: 38024, dtype: object

EXPORT DATASET CON TESTO PULITO

In [6]:
tweet["text_def"].to_csv("C:/Users/Angela/Desktop/SARDINE/dataset/tweets_puliti_per_sentiment.csv")

NameError: name 'tweet' is not defined

IMPORT RISULTATI SENTIMENT NRC CON R

In [4]:
tweet = pd.read_csv("C:/Users/Angela/Desktop/SARDINE/dataset/pulizia_sent.csv")

In [5]:
sent = pd.read_csv("C:/Users/Angela/Desktop/SARDINE/dataset/sa_nrc_lemma.csv")

In [160]:
len(sent)

31003

In [6]:
result = pd.concat([tweet, sent], axis=1, sort=False)

DATASET COMPLETO - testo grezzo + pulito + sentiment + cluster

In [131]:
selection = result[["text", "text_def",'anger', 'anticipation', 'disgust', 'fear', 'joy', 'sadness', 'surprise', 
                    'trust', 'negative', 'positive', 'name_y', 'cluster_y']]

In [161]:
result.text_def.head(40)

0     scherzetto di che domanda alle sardine cosa ne...
1     le famose piazze delle sardine contro l’odio a...
2     la confusione de sto ragazzo è palese e lampan...
3     mattia santori scende in piazza per bonaccini ...
4     se la gente partecipa nelle piazze va bene ma ...
5     ma chi glielo dice a questa sardina che al gov...
6     io ho solo una domanda ma esigo una risposta m...
7     tutti questi complimenti da parte del pd e di ...
8     dimaio dobbiamo lavorare per i prossimi  anni ...
9      vi danno pure troppo spago sardine pagate con...
10     il coglione è lideatore e il finanziatore del...
11    salvini sardine chiedono che un ministro non p...
12    di maio «nazionalizzare la popolare di bari be...
13    gassman con le sardinechi gassman quello che d...
14    in piazza a roma la morte dellintelligenza amm...
15    il leader delle sardine gli elettori della leg...
16    il leader delle sardine siamo evidentemente vi...
17    matteo salvini durissimo con mattia santori le...
18      manifestazioni in tutto il paese milioni di ...
19    i papaboys di bergoglio benedicono le sardines...
20    altra mini inchiesta di che stavolta chiede al...
21    prima il ciuccio poi lulivo e adesso i pdioti ...
22    quindi bonaccini dice che non è del pd giusepp...
23    il mes è anti costituzionale ci sarà questo ti...
24    endorsement di orlando alle sardine  chiedono ...
25    rizzo non cè nulla di più organizzato di un mo...
26    casapound fa un tweet le sardine abboccano e v...
27    rizzo ha appena dato dei fascisti alle sardine...
28    conte al corriere siamo pronti per la maratona...
29    manca solo la delegazione di confindustria la ...
30    tgpost rizzo le bandiere europee le mandate vi...
31    tutti pazzi per le sardinedal paigiano al card...
32    anche le sardine provano ad usare e strumental...
33    sardine democratica e pacifica salvini per il ...
34    conte corteggia le sardine dl sicurezza lo cam...
35    chiunque neghi che le sardine siano lennesima ...
36    viva la spontaneità in puazza san giovanni del...
37    dopo i s pronte le sardine altra distrazione d...
38    sardine in piazza a sassari risposta tiepida d...
39    il vero volto delle sardine antisemite terrori...
Name: text_def, dtype: object

In [148]:
valmax = selection.positive.argmax()
valmax

C:\Users\Angela\Anaconda3\envs\python3.6\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 'argmax' is deprecated, use 'idxmax' instead. The behavior of 'argmax'
will be corrected to return the positional maximum in the future.
Use 'series.values.argmax' to get the position of the maximum now.
  """Entry point for launching an IPython kernel.

10518

In [11]:
pos = selection.groupby(['cluster'])['positive'].mean().reset_index()
neg = selection.groupby(['cluster'])['negative'].mean().reset_index()
anger = selection.groupby(['cluster'])['anger'].mean().reset_index()
anticipation = selection.groupby(['cluster'])['anticipation'].mean().reset_index()
disgust = selection.groupby(['cluster'])['disgust'].mean().reset_index()
fear = selection.groupby(['cluster'])['fear'].mean().reset_index()
joy = selection.groupby(['cluster'])['joy'].mean().reset_index()
sadness = selection.groupby(['cluster'])['sadness'].mean().reset_index()
surprise = selection.groupby(['cluster'])['surprise'].mean().reset_index()
trust = selection.groupby(['cluster'])['trust'].mean().reset_index()

In [12]:
mpc = pd.concat([pos, neg, anger, anticipation, disgust, fear,joy,sadness,surprise,trust], axis=0, sort=False)
mpc = mpc.groupby("cluster").mean().reset_index()
mpc.to_csv("risultati_sentiment_mention.csv", index = False)

In [ ]:
mpc.iloc[[0,1,3,5,8],]
#mentions, mean per cluster

In [ ]:
mpc.to_csv("C:/Users/Angela/Desktop/SARDINE/dataset/nrc_result_mentions.csv")

In [ ]:
res_grouped = result

In [ ]:
res_grouped_clu = res_grouped[res_grouped["cluster_y"] == 3]
tpos = res_grouped_clu.loc[res_grouped_clu["trust"].argmax(),:]

#  HASHTAG

In [ ]:
hashtag = pd.read_csv("C:/Users/Angela/Desktop/SARDINE/dataset/df_finale_true_cluster_hashtags.csv")

In [ ]:
hashtag

In [ ]:
hashtag["text_def"] = hashtag["text"].apply(remove_mentions)
hashtag["text_def"] = hashtag["text_def"].apply(remove_url)
hashtag["text_def"]= hashtag["text_def"].replace("\n", "", regex = True)
hashtag["text_def"] = hashtag["text_def"].replace("#", "", regex = True)
hashtag["text_def"] = hashtag["text_def"].replace("\n", "", regex = True)
hashtag["text_def"] = hashtag["text_def"].replace("-", "", regex = True)
hashtag["text_def"] = hashtag["text_def"].replace("_", "", regex = True)
hashtag["text_def"] = hashtag["text_def"].replace(",", "", regex = True)
hashtag["text_def"] = hashtag["text_def"].replace(":", "", regex = True)
hashtag["text_def"] = hashtag["text_def"].replace(";", "", regex = True)
hashtag["text_def"] = hashtag["text_def"].replace("\"", "", regex = True)
hashtag["text_def"] = hashtag["text_def"].replace("\'", "", regex = True)
hashtag["text_def"] = hashtag["text_def"].replace("=", "", regex = True)
hashtag["text_def"] = hashtag["text_def"].replace("\?", "", regex = True)
hashtag["text_def"] = hashtag["text_def"].replace("!", "", regex = True)
hashtag["text_def"] = hashtag["text_def"].replace("\.", " ", regex = True)
hashtag["text_def"] = hashtag["text_def"].replace("\(", "", regex = True)
hashtag["text_def"] = hashtag["text_def"].replace("\)", "", regex = True)
hashtag["text_def"] = hashtag["text_def"].replace("\“", "", regex = True)
hashtag["text_def"] = hashtag["text_def"].replace("\s+", " ", regex = True)
hashtag["text_def"] = hashtag["text_def"].replace("\d*", "", regex = True)
hashtag["text_def"] = hashtag["text_def"].replace("RT", "", regex = True)
hashtag["text_def"] = hashtag["text_def"].str.lower()
hashtag["text_def"] = hashtag["text_def"].apply(remove_emoji)

In [ ]:
hashtag["text_def"]

In [ ]:
hashtag["text_def"].to_csv("C:/Users/Angela/Desktop/SARDINE/dataset/tweets_puliti_per_sentiment_hashtag.csv")

import

In [18]:
hashtag = pd.read_csv("C:/Users/Angela/Desktop/SARDINE/dataset/pulizia_sent_hash.csv")

In [21]:
sent_hashtag = pd.read_csv("C:/Users/Angela/Desktop/SARDINE/dataset/sa_nrc_lemma_hash.csv")

In [22]:
result_hashtag = pd.concat([hashtag, sent_hashtag], axis=1, sort=False)

In [23]:
result_hashtag

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,@mentions,account_created_at,account_description,account_favourites_count,account_followers_count,account_friends_count,account_listed_count,...,anger,anticipation,disgust,fear,joy,sadness,surprise,trust,negative,positive
0,0,0,0,"AMorelliMilano,_GrayDorian",2017-10-25 13:43:20,NN DATEMI CONSIGLI....SO SBAGLIARE DA ME.,26620,459,251,2,...,0,0,0,0,1,0,0,2,0,2
1,1,1,1,FrancescoLollo1,2017-10-25 13:43:20,NN DATEMI CONSIGLI....SO SBAGLIARE DA ME.,26806,462,251,2,...,1,1,0,0,0,0,0,1,1,4
2,2,2,2,chiossimanuela2,2017-10-25 13:43:20,NN DATEMI CONSIGLI....SO SBAGLIARE DA ME.,26808,462,251,2,...,1,0,1,1,0,0,1,0,1,0
3,3,3,3,BarillariM5S,2017-10-25 13:43:20,NN DATEMI CONSIGLI....SO SBAGLIARE DA ME.,27029,467,250,2,...,1,2,0,1,1,3,2,4,3,2
4,4,4,4,vitocontesi,2017-10-25 13:43:20,NN DATEMI CONSIGLI....SO SBAGLIARE DA ME.,27029,467,250,2,...,1,0,1,1,0,1,1,0,3,1
5,5,5,5,"nonelarena,matteosalvinimi",2017-10-25 13:43:20,NN DATEMI CONSIGLI....SO SBAGLIARE DA ME.,27029,467,250,2,...,0,0,0,0,0,0,0,1,0,1
6,6,6,6,UmbertoNew,2017-10-25 13:43:20,NN DATEMI CONSIGLI....SO SBAGLIARE DA ME.,27029,467,250,2,...,0,1,0,0,1,1,1,1,3,3
7,7,7,7,doluccia16,2018-10-24 22:43:19.999999762,NaN,324174,985,383,0,...,0,1,0,0,0,0,0,1,1,1
8,8,8,8,ChiodiDonatella,2018-10-24 22:43:19.999999762,NaN,324665,983,383,0,...,0,1,0,0,1,0,0,3,0,4
9,9,9,9,"AMorelliMilano,_GrayDorian",2018-10-24 22:43:19.999999762,NaN,324665,983,383,0,...,0,0,0,0,0,0,0,0,0,0
10,10,10,10,ZioIllo,2018-10-24 22:43:19.999999762,NaN,324665,983,383,0,...,1,0,1,1,0,0,1,0,1,0
11,11,11,11,25O319,2018-10-24 22:43:19.999999762,NaN,324665,983,383,0,...,0,2,0,1,0,1,0,1,1,2
12,12,12,12,"LuciaBorgonzoni,fracchio_",2018-10-24 22:43:19.999999762,NaN,324665,983,383,0,...,4,1,2,2,0,1,1,0,5,1
13,13,13,13,scarpettavenere,2018-10-24 22:43:19.999999762,NaN,324665,983,383,0,...,0,0,0,0,0,0,0,0,0,1
14,14,14,14,chiaralucetw,2018-10-24 22:43:19.999999762,NaN,324665,983,383,0,...,2,0,0,2,1,0,0,1,4,2
15,15,15,15,fabrizio_sn,2018-10-24 22:43:19.999999762,NaN,324665,983,383,0,...,0,0,0,0,0,0,0,0,0,0
16,16,16,16,NicolaPorro,2018-10-24 22:43:19.999999762,NaN,324665,983,383,0,...,1,2,0,1,1,0,0,1,2,1
17,17,17,17,_GrayDorian,2018-10-24 22:43:19.999999762,NaN,324665,983,383,0,...,1,0,1,1,0,0,1,1,1,0
18,18,18,18,ChiodiDonatella,2018-10-24 22:43:19.999999762,NaN,324665,983,383,0,...,4,3,2,4,2,2,0,2,5,2
19,19,19,19,valy_s,2018-10-24 22:43:19.999999762,NaN,324665,983,383,0,...,0,0,0,0,0,0,0,0,0,1
20,20,20,20,benq_antonio,2018-10-24 22:43:19.999999762,NaN,327257,991,382,0,...,2,2,1,1,0,1,0,1,2,3
21,21,21,21,BettyM64,2018-10-24 22:43:19.999999762,NaN,327257,991,382,0,...,3,2,0,1,1,1,0,1,6,1
22,22,22,22,LisadaCa,2018-10-24 22:43:19.999999762,NaN,327257,991,382,0,...,1,0,1,1,1,1,1,3,1,5
23,23,23,23,25O319,2018-10-24 22:43:19.999999762,NaN,327257,991,382,0,...,2,0,1,1,0,1,1,1,2,1
24,24,24,24,GiuseppePalma78,2018-10-24 22:43:19.999999762,NaN,327257,991,382,0,...,0,2,0,0,0,0,0,0,0,2
25,25,25,25,AlessandroCere7,Wed Oct 24 22:43:11 +0000 2018,NaN,324478,985,383,0,...,0,1,0,0,1,1,1,1,0,2
26,26,26,26,todorov_denis,Wed Oct 24 22:43:11 +0000 2018,NaN,324478,985,383,0,...,1,0,1,1,0,0,1,0,2,0
27,27,27,27,NicolaPorro,Wed Oct 24 22:43:11 +0000 2018,NaN,324478,985,383,0,...,3,3,1,1,0,0,0,0,3,1
28,28,28,28,NicolaPorro,Wed Oct 24 22:43:11 +0000 2018,NaN,322903,987,382,0,...,3,3,1,1,0,0,0,0,3,1
29,29,29,29,SYuliaSalazar,Wed Oct 24 22:43:11 +0000 2018,NaN,322989,987,382,0,...,1,0,1,1,0,0,0,1,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22374,28147,28147,28282,NaN,Fri Apr 03 21:01:14 +0000 2009,NaN,3857,64,311,2,...,0,0,0,0,0,0,0,0,0,0
22375,28148,28148,28283,NaN,Wed Jan 09 20:02:52 +0000 2013,Bachelor's degree in politics science- interna...,26,77,306,0,...,0,0,0,0,0,0,0,0,0,1
22376,28149,28149,28284,sruotolo1,Thu Mar 27 06:59:21 +0000 2014,NaN,3817,93,123,0,...,0,0,1,0,2,0,0,0,1,3
22377,28150,28150,28285,AberWhaat,Sat Aug 25 18:13:56 +0000 2018,i Patridioti ci porteranno allo sfascio immers...,5398,1556,1494,1,...,0,0,0,0,1,0,0,2,0,3
22378,28151,28151,28286,NaN,Fri Mar 28 22:01:21 +0000 2014,#AliceinWonderland❤👨‍👩‍👧\n\nOCR Athlete\n💚 Kaw...,37063,364,1545,12,...,0,0,0,0,0,0,0,0,0,0
22379,28152,28152,28287,virginiaraggi,Sat Feb 04 23:34:09 +0000 2012,5 stelle e basta!,61567,2343,2950,69,...,0,3,0,0,2,1,2,1,0,7
22380,28153,28153,28288,MilkoSichinolfi,Mon Jan 30 12:36:03 +0000 2012,#facciamorete,32919,256,185,3,...,0,1,0,0,1,1,1,1,0,2
22381,28154,28154,28289,pietroraffa,Mon Jan 30 12:36:03 +0000 2012,#facciamorete,32920,256,185,3,...,0,0,0,0,0,0,0,0,0,0
22382,28155,28155,28290,sruotolo1,Fri Apr 19 15:10:45 +0000 2019,NaN,2540,5,63,0,...,1,1,0,0,0,2,1,0,2,0
22383,28156,28156,28291,debufred,Fri Jul 12 14:28:46 +0000 2019,NaN,1665,35,55,0,...,0,0,0,0,0,0,0,1,0,3
22384,28158,28158,28293,Gio_Bonometto,Fri Apr 29 08:41:21 +0000 2011,(thinking mode),505,320,821,6,...,0,1,0,0,3,0,1,0,0,5
22385,28159,28159,28294,NaN,Thu Jun 21 11:44:56 +0000 2012,👽,1848,56,178,0,...,0,0,0,0,0,0,0,0,0,0
22386,28160,28160,28295,nabelb,Thu Oct 23 12:12:50 +0000 2014,Here for the news and views.\nI live expectantly,269,1217,3678,94,...,0,0,0,0,0,0,0,0,0,0
22387,28161,28161,28296,larespublica1,Thu Oct 23 12:12:50 +0000 2014,Here for the news and views.\nI live expectantly,269,1217,3678,94,...,0,0,0,0,0,0,0,1,0,0
22388,28162,28162,28297,IlCastiga,Fri Jul 05 17:28:11 +0000 2019,Texwiller,531,6,58,0,...,0,0,0,0,0,1,0,1,1,1
22389,28163,28163,28298,fiomnet,Fri Dec 04 22:14:22 +0000 2009,Non ci tengo a sapere i fatti miei,15188,119,259,2,...,0,0,0,0,0,0,0,0,0,0
22390,28164,28164,28299,NaN,Fri Dec 23 01:35:01 +0000 2011,#psychologist #PoliticalPsychology . Associazi...,223401,30898,7731,437,...,2,2,3,2,1,0,1,0,4,2
22391,28167,28167,28302,NaN,Sat Jul 23 20:06:31 +0000 2011,Cassa dritta,5709,2200,2216,33,...,0,0,0,0,0,0,0,0,0,0
22392,28168,28168,28303,NaN,Sun Oct 20 23:20:43 +0000 2013,Roma-Monterotondo-Cisterna (LT)-Colleferro-Mon...,51612,323,342,2,...,0,0,0,0,0,0,0,0,0,0
22393,28169,28169,28304,pietroraffa,Wed Oct 31 12:05:25 +0000 2018,NaN,4496,22,186,0,...,0,0,1,0,0,0,0,1,1,0
22394,28170,28170,28305,SimoneVarca,Mon Jun 29 18:47:52 +0000 2009,Italian living in UK for 3 decades. European. ...,96520,16288,12157,29,...,2,0,0,1,0,1,0,0,2,0
22395,28171,28171,28306,nzingaretti,Wed Apr 04 14:21:34 +0000 2012,Certified Tourist Guide for Cuneo-Alba Provinc...,385,478,258,54,...,0,0,0,0,0,0,0,1,0,1
22396,28172,28172,28307,nzingaretti,Sat Dec 14 02:41:03 +0000 2019,un gruppo EUROPEO di fumatori stanchi di esser...,0,1,8,0,...,0,2,0,0,3,1,1,4,0,8
22397,28173,28173,28308,NaN,Wed Jan 23 15:48:56 +0000 2013,Senatore #ItaliaViva @italiaviva Sindaco di #...,246,4036,189,78,...,0,2,0,0,4,0,3,3,0,6
22398,28174,28174,28309,NaN,Wed Jan 23 15:48:56 +0000 2013,Senatore #ItaliaViva @italiaviva Sindaco di #...,246,4036,189,78,...,0,2,0,0,4,0,3,3,0,6
22399,28175,28175,28310,NaN,Tue Sep 18 14:22:48 +0000 2012,Lucano. Trapiantato a Perugia dal lontano 2006...,7794,1664,1819,19,...,0,0,0,0,0,0,0,0,0,1
22400,28176,28176,28311,NicolaPorro,Sat Oct 04 20:37:20 +0000 2014,NaN,8763,60,347,2,...,5,2,2,4,1,2,1,1,7,1
22401,28177,28177,28312,NaN,Sun Jul 01 13:55:42 +0000 2018,Weird things and amenities from All over the w...,0,14,71,0,...,0,0,0,0,0,0,0,0,0,0
22402,28178,28178,28313,pietroraffa,Thu Jan 26 17:23:27 +0000 2012,"Toppe di inesistenza, calce o cenere\nPronte a...",26338,1424,668,50,...,0,0,0,0,0,0,0,0,0,0
22403,28179,28179,28314,IlCastiga,Mon Sep 21 13:11:43 +0000 2009,Sie müssen sich von diesen dem neunzehnten Ja...,28779,146,81,0,...,0,0,0,0,0,1,0,1,1,1

In [27]:
selection_hashtag = result_hashtag[["text", 'anger', 'anticipation', 'disgust', 'fear', 'joy', 'sadness', 'surprise', 
                    'trust', 'negative', 'positive', 'cluster_y']]

In [31]:
selection_hashtag

,text,anger,anticipation,disgust,fear,joy,sadness,surprise,trust,negative,positive,cluster_y
0,scherzetto di che domandare alla cosa ne pensa...,0,0,0,0,1,0,0,2,0,2,0
1,la famoso piazza della contro l odiare alla fi...,1,1,0,0,0,0,0,1,1,4,0
2,io avere solere una domandare ma esigere una r...,1,0,1,1,0,0,1,0,1,0,0
3,tutto questo complimento da partire del pd e d...,1,2,0,1,1,3,2,4,3,2,0
4,dovere lavorare per il prossimo anno del cos...,1,0,1,1,0,1,1,0,3,1,0
5,sardina chiedere che un ministrare non poter...,0,0,0,0,0,0,0,1,0,1,0
6,con la chi gassman quello che dovere prender...,0,1,0,0,1,1,1,1,3,3,0
7,il leader della essere evidentemente vicino al...,0,1,0,0,0,0,0,1,1,1,2
8,il di benedire la sabato prossimo essere in pi...,0,1,0,0,1,0,0,3,0,4,2
9,altro miniare inchiesta di che stavolta chiede...,0,0,0,0,0,0,0,0,0,0,2
10,quindi dire che non essere del pd dire che non...,1,0,1,1,0,0,1,0,1,0,2
11,il essere anti costituzionale ci essere ques...,0,2,0,1,0,1,0,1,1,2,2
12,endorsement di orlare alla chiedere una politi...,4,1,2,2,0,1,1,0,5,1,2
13,rizzare non c essere nullo di molto organizzar...,0,0,0,0,0,0,0,0,0,1,2
14,fare un tweet la abboccare e andare in tilt ...,2,0,0,2,1,0,0,1,4,2,2
15,avere appena datare dio fascista alla essere...,0,0,0,0,0,0,0,0,0,0,2
16,al corriera essere pronto per la maratona de...,1,2,0,1,1,0,0,1,2,1,2
17,rizzare la bandiera europeo la mandare via o...,1,0,1,1,0,0,1,1,1,0,2
18,tutto pazzo per la dal partigiano al cardinale...,4,3,2,4,2,2,0,2,5,2,2
19,anche la provare ad usare e strumentalizzare l...,0,0,0,0,0,0,0,0,0,1,2
20,democratico e pacifico per il potere si mang...,2,2,1,1,0,1,0,1,2,3,2
21,dopo il s pronto la altro distrazione di massa...,3,2,0,1,1,1,0,1,6,1,2
22,il vero voltare della antisemita terrorista ch...,1,0,1,1,1,1,1,3,1,5,2
23,la essere un movimentare che simpatizzare per ...,2,0,1,1,0,1,1,1,2,1,2
24,la proposta della essere il vuotare cosmico tu...,0,2,0,0,0,0,0,0,0,2,2
25,o bello ciao bello ciao bello ciao ciao ciao,0,1,0,0,1,1,1,1,0,2,2
26,secondare monte in italia ci pensare la sardin...,1,0,1,1,0,0,1,0,2,0,2
27,cosa c essere di molto populista di un movimen...,3,3,1,1,0,0,0,0,3,1,2
28,cosa c essere di molto populista di un movimen...,3,3,1,1,0,0,0,0,3,1,2
29,razzista ma una parola su questo coglione no...,1,0,1,1,0,0,0,1,2,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...
22374,non mi legare,0,0,0,0,0,0,0,0,0,0,11
22375,come essere profondere il mare,0,0,0,0,0,0,0,0,0,1,10
22376,a roma c essere una espressione molto popola...,0,0,1,0,2,0,0,0,1,3,11
22377,a gremire di a rappresentare la vero italia ...,0,0,0,0,1,0,0,2,0,3,11
22378,in pratico la essere stare capace di fare quel...,0,0,0,0,0,0,0,0,0,0,0
22379,essere bello vedere tanto partecipazione di ci...,0,3,0,0,2,1,2,1,0,7,1
22380,oggi roma essere molto bello che mai,0,1,0,0,1,1,1,1,0,2,10
22381,avere presentire il concetto di marea eccolo qui,0,0,0,0,0,0,0,0,0,0,10
22382,buongiorno restare così come essere orgogliosa...,1,1,0,0,0,2,1,0,2,0,1
22383,pppasolini lucidare attuale efficace,0,0,0,0,0,0,0,1,0,3,11
22384,molto gente che al primo maggio sapere giovann...,0,1,0,0,3,0,1,0,0,5,11
22385,il sistemare vincere sempre la ne essere un es...,0,0,0,0,0,0,0,0,0,0,1
22386,non mi legare,0,0,0,0,0,0,0,0,0,0,11
22387,la avere riempire piazzare sapere giovanni,0,0,0,0,0,0,0,1,0,0,11
22388,la volere una tazza di the essere venuto in ...,0,0,0,0,0,1,0,1,1,1,11
22389,la riempiono piazzare sapere giovanni a la c e...,0,0,0,0,0,0,0,0,0,0,11
22390,risuonare per e un brivido il mettere sempre...,2,2,3,2,1,0,1,0,4,2,10
22391,dall assaltare a piazzare del popolare alla ...,0,0,0,0,0,0,0,0,0,0,11
22392,insomma il pd riempie la piazza solere se non ...,0,0,0,0,0,0,0,0,0,0,1
22393,che spettacolo ragazzo,0,0,1,0,0,0,0,1,1,0,11
22394,rubare questo foto da facebook per condividere...,2,0,0,1,0,1,0,0,2,0,11
22395,il puntare della proposta lanciato dalla rec...,0,0,0,0,0,0,0,1,0,1,1
22396,grazia per avere rendere così bello per la pas...,0,2,0,0,3,1,1,4,0,8,11
22397,la piazzare di roma valere molto di tanto paro...,0,2,0,0,4,0,3,3,0,6,1
22398,la piazzare di roma valere molto di tanto paro...,0,2,0,0,4,0,3,3,0,6,1
22399,non sapere cosa ne essere di questo grazia a l...,0,0,0,0,0,0,0,0,0,1,11
22400,nessuno dire che la sterlina e la borsa esse...,5,2,2,4,1,2,1,1,7,1,2
22401,alimortè,0,0,0,0,0,0,0,0,0,0,11
22402,avere presentire il concetto di marea eccolo qui,0,0,0,0,0,0,0,0,0,0,11
22403,la volere una tazza di the essere venuto in ...,0,0,0,0,0,1,0,1,1,1,11

In [32]:
pos_hashtag = selection_hashtag.groupby(['cluster_y'])['positive'].mean().reset_index()
neg_hashtag = selection_hashtag.groupby(['cluster_y'])['negative'].mean().reset_index()
anger_hashtag = selection_hashtag.groupby(['cluster_y'])['anger'].mean().reset_index()
anticipation_hashtag = selection_hashtag.groupby(['cluster_y'])['anticipation'].mean().reset_index()
disgust_hashtag = selection_hashtag.groupby(['cluster_y'])['disgust'].mean().reset_index()
fear_hashtag = selection_hashtag.groupby(['cluster_y'])['fear'].mean().reset_index()
joy_hashtag = selection_hashtag.groupby(['cluster_y'])['joy'].mean().reset_index()
sadness_hashtag = selection_hashtag.groupby(['cluster_y'])['sadness'].mean().reset_index()
surprise_hashtag = selection_hashtag.groupby(['cluster_y'])['surprise'].mean().reset_index()
trust_hashtag = selection_hashtag.groupby(['cluster_y'])['trust'].mean().reset_index()

In [43]:
mpc_hashtag = pd.concat([pos_hashtag, neg_hashtag, anger_hashtag, anticipation_hashtag, 
                         disgust_hashtag, fear_hashtag,joy_hashtag,sadness_hashtag,surprise_hashtag,trust_hashtag], axis=0, sort=False)

In [1]:
#mpc_hashtag

In [46]:
mpc_hashtag = mpc_hashtag.groupby("cluster_y").mean().reset_index()

In [47]:
mpc_hashtag

,cluster_y,positive,negative,anger,anticipation,disgust,fear,joy,sadness,surprise,trust
0,0,1.631506,1.453488,0.651993,0.560631,0.373477,0.639812,0.464009,0.512182,0.325305,0.825858
1,1,1.552764,1.060302,0.547111,0.512563,0.280779,0.357098,0.450063,0.424309,0.273869,0.812500
2,2,1.333767,1.163194,0.621962,0.603299,0.309896,0.526910,0.480469,0.546007,0.392361,0.738715
3,3,1.451454,1.244805,0.551568,0.503589,0.315074,0.478655,0.421232,0.457877,0.279184,0.782773
4,10,1.551935,0.602954,0.229952,0.514586,0.125229,0.242646,0.545466,0.378494,0.307580,0.735018
5,11,1.336851,0.697240,0.296672,0.419237,0.169643,0.295455,0.425325,0.357143,0.232955,0.656250

In [48]:
mpc_hashtag.to_csv("risultati_sentiment_hashtag.csv", index = False)

In [42]:
mpc_hashtag

,cluster_y,positive,cluster_y,negative,cluster_y,anger,cluster_y,anticipation,cluster_y,disgust,cluster_y,fear,cluster_y,joy,cluster_y,sadness,cluster_y,surprise,cluster_y,trust
0,0,1.631506,0,1.453488,0,0.651993,0,0.560631,0,0.373477,0,0.639812,0,0.464009,0,0.512182,0,0.325305,0,0.825858
1,1,1.552764,1,1.060302,1,0.547111,1,0.512563,1,0.280779,1,0.357098,1,0.450063,1,0.424309,1,0.273869,1,0.812500
2,2,1.333767,2,1.163194,2,0.621962,2,0.603299,2,0.309896,2,0.526910,2,0.480469,2,0.546007,2,0.392361,2,0.738715
3,3,1.451454,3,1.244805,3,0.551568,3,0.503589,3,0.315074,3,0.478655,3,0.421232,3,0.457877,3,0.279184,3,0.782773
4,10,1.551935,10,0.602954,10,0.229952,10,0.514586,10,0.125229,10,0.242646,10,0.545466,10,0.378494,10,0.307580,10,0.735018
5,11,1.336851,11,0.697240,11,0.296672,11,0.419237,11,0.169643,11,0.295455,11,0.425325,11,0.357143,11,0.232955,11,0.656250

In [35]:
mpc_hashtag.drop(mpc_hashtag.columns[[0,2,4,6,8,10,12,14,16,18]],axis=1,inplace=True)

In [37]:
mpc_hashtag

,positive,negative,anger,anticipation,disgust,fear,joy,sadness,surprise,trust
0,1.631506,1.453488,0.651993,0.560631,0.373477,0.639812,0.464009,0.512182,0.325305,0.825858
1,1.552764,1.060302,0.547111,0.512563,0.280779,0.357098,0.450063,0.424309,0.273869,0.812500
2,1.333767,1.163194,0.621962,0.603299,0.309896,0.526910,0.480469,0.546007,0.392361,0.738715
3,1.451454,1.244805,0.551568,0.503589,0.315074,0.478655,0.421232,0.457877,0.279184,0.782773
4,1.551935,0.602954,0.229952,0.514586,0.125229,0.242646,0.545466,0.378494,0.307580,0.735018
5,1.336851,0.697240,0.296672,0.419237,0.169643,0.295455,0.425325,0.357143,0.232955,0.656250

In [ ]:
mpc_hashtag.to_csv("C:/Users/Angela/Desktop/SARDINE/dataset/nrc_result_hashtag.csv")

# BOT

In [94]:
bot = pd.read_csv("C:/Users/Angela/Desktop/SARDINE/dataset/bot_dataset.csv")

In [96]:
def remove_mentions(x):
    p = re.sub(r'@([^\s:]+)','', x)
    return p

def remove_url(x):
    p = re.sub(r'http\S+','', x)
    return p

def remove_emoji(x):
    p = re.sub(r'(\<u+\S*\>)', '',x)
    return p

In [97]:
bot["text_def"] = bot["text"].apply(remove_mentions)
bot["text_def"] = bot["text"].apply(remove_url)
bot["text_def"]= bot["text_def"].replace("\n", "", regex = True)
bot["text_def"] = bot["text_def"].replace("#", "", regex = True)
bot["text_def"] = bot["text_def"].replace("-", "", regex = True)
bot["text_def"] = bot["text_def"].replace("_", "", regex = True)
bot["text_def"] = bot["text_def"].replace(",", "", regex = True)
bot["text_def"] = bot["text_def"].replace(":", "", regex = True)
bot["text_def"] = bot["text_def"].replace(";", "", regex = True)
bot["text_def"] = bot["text_def"].replace("\"", "", regex = True)
bot["text_def"] = bot["text_def"].replace("\'", "", regex = True)
bot["text_def"] = bot["text_def"].replace("=", "", regex = True)
bot["text_def"] = bot["text_def"].replace("\?", "", regex = True)
bot["text_def"] = bot["text_def"].replace("!", "", regex = True)
bot["text_def"] = bot["text_def"].replace("\.", " ", regex = True)
bot["text_def"] = bot["text_def"].replace("\(", "", regex = True)
bot["text_def"] = bot["text_def"].replace("\)", "", regex = True)
bot["text_def"] = bot["text_def"].replace("\“", "", regex = True)
bot["text_def"] = bot["text_def"].replace("\s+", " ", regex = True)
bot["text_def"] = bot["text_def"].replace("\d*", "", regex = True)
bot["text_def"] = bot["text_def"].replace("RT", "", regex = True)
bot["text_def"] = bot["text_def"].str.lower()
bot["text_def"] = bot["text_def"].apply(remove_emoji)

In [98]:
bot["text_def"].to_csv("C:/Users/Angela/Desktop/SARDINE/dataset/tweets_puliti_per_sentiment_bot.csv")

In [ ]:
sent_bot = pd.read_csv("C:/Users/Angela/Desktop/SARDINE/dataset/sa_nrc_bot_lemma.csv")

In [ ]:
result_bot = pd.concat([bot, sent_bot], axis=1, sort=False)

In [ ]:
selection_bot = result_bot[["text", "text_def", 'anger', 'anticipation', 'disgust', 'fear', 'joy', 'sadness', 'surprise', 
                    'trust', 'negative', 'positive']]

In [ ]:
selection_bot

In [ ]:
pos_bot = selection_bot['positive'].mean()
neg_bot = selection_bot['negative'].mean()
anger_bot = selection_bot['anger'].mean()
anticipation_bot = selection_bot['anticipation'].mean()
disgust_bot = selection_bot['disgust'].mean()
fear_bot = selection_bot['fear'].mean()
joy_bot = selection_bot['joy'].mean()
sadness_bot = selection_bot['sadness'].mean()
surprise_bot = selection_bot['surprise'].mean()
trust_bot = selection_bot['trust'].mean()

In [ ]:
data =  {"positive" :[pos_bot], "negative": [neg_bot], "anger":[anger_bot], 
                          "anticipation":[anticipation_bot], "disgust_bot": [disgust_bot], 
                          "fear": [fear_bot], "joy": [joy_bot],"sadness":[sadness_bot],
                          "surprise":[surprise_bot],"trust":[trust_bot]}
mpc_bot = pd.DataFrame(data)

In [ ]:
lower_bound = []
upper_bound = []
diff_mean = []
significa = []

clu0pos_mean = mpc_bot.positive.mean()
clu0neg_mean = mpc_bot.negative.mean()
clu0pos_std = mpc_bot.positive.std()
clu0neg_std = mpc_bot.negative.std()
numerosità = len(mpc_bot)

err_st = sqrt((clu0pos_std**2/numerosità)+(clu0neg_std**2/numerosità))
alfa = 1.96
lower_bound.append(clu0pos_mean - clu0neg_mean - alfa*err_st)
upper_bound.append(clu0pos_mean - clu0neg_mean + alfa*err_st)
diff_mean.append(clu0pos_mean - clu0neg_mean)
if (clu0pos_mean - clu0neg_mean >= clu0pos_mean - clu0neg_mean + alfa*err_st) or (clu0pos_mean - clu0neg_mean <= clu0pos_mean - clu0neg_mean - alfa*err_st):
    significa.append("C'è differenza")
else: 
    significa.append("Non c'è differenza")

# EVENTO ROMA

In [7]:
import datetime

In [17]:
result_roma = result

In [114]:
def find_roma(x):
    if "roma" in x:
        return (True)
    else:
        return(False)

In [120]:
def find_emilia(x):
    if "romagna" in x:
        return (True)
    else:
        return(False)

In [115]:
result["roma"] = result["hashtags"].apply(find_roma)

In [121]:
result["emilia"] = result["hashtags"].apply(find_emilia)

In [116]:
result["roma"].value_counts()

False    28086
True      2917
Name: roma, dtype: int64

In [124]:
roma = result[(result["roma"] == True) & (result["emilia"] == False)]

In [126]:
roma["hashtags"].head()

19                       papaboys,bergoglio,sardine,roma
119                                             romanons
143                   romanonsilega,sardine,facciamorete
144                                sardine,romanonsilega
145    sottoilcielodiroma,sardine,bellaciao,piazzasan...
Name: hashtags, dtype: object

In [130]:
len(roma)

2793

In [127]:
pos_roma = roma['positive'].mean()
neg_roma = roma['negative'].mean()
anger_roma = roma['anger'].mean()
anticipation_roma = roma['anticipation'].mean()
disgust_roma = roma['disgust'].mean()
fear_roma = roma['fear'].mean()
joy_roma = roma['joy'].mean()
sadness_roma = roma['sadness'].mean()
surprise_roma = roma['surprise'].mean()
trust_roma = roma['trust'].mean()

In [128]:
data =  {"positive" :[pos_roma], "negative": [neg_roma], "anger":[anger_roma], 
                          "anticipation":[anticipation_roma], "disgust_roma": [disgust_roma], 
                          "fear": [fear_roma], "joy": [joy_roma],"sadness":[sadness_roma],
                          "surprise":[surprise_roma],"trust":[trust_roma]}
mpc_roma = pd.DataFrame(data)

In [129]:
mpc_roma

,positive,negative,anger,anticipation,disgust_roma,fear,joy,sadness,surprise,trust
0,1.446115,0.553885,0.261368,0.359828,0.139635,0.209094,0.535983,0.380594,0.209452,0.620122

In [149]:
lower_bound = []
upper_bound = []
diff_mean = []
significa = []

clu0pos_mean = roma.positive.mean()
clu0neg_mean = roma.negative.mean()
clu0pos_std = roma.positive.std()
clu0neg_std = roma.negative.std()
numerosità = 2793

err_st = math.sqrt((clu0pos_std**2/numerosità)+(clu0neg_std**2/numerosità))
alfa = 1.96
lower_bound.append(clu0pos_mean - clu0neg_mean - alfa*err_st)
upper_bound.append(clu0pos_mean - clu0neg_mean + alfa*err_st)
diff_mean.append(clu0pos_mean - clu0neg_mean)
if (clu0pos_mean - clu0neg_mean >= clu0pos_mean - clu0neg_mean + alfa*err_st) or (clu0pos_mean - clu0neg_mean <= clu0pos_mean - clu0neg_mean - alfa*err_st):
    significa.append("C'è differenza")
else: 
    significa.append("Non c'è differenza")

In [150]:
significa

["Non c'è differenza"]

# BREXIT

In [69]:
import math

In [158]:
len(result)

31003

ValueError: No axis named 16486 for object type <class 'pandas.core.frame.DataFrame'>

In [178]:
a = result[result["screen_name"] == "MariangelaErcu3"]

In [179]:
a

,index,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,@mentions,account_created_at,account_description,account_favourites_count,account_followers_count,account_friends_count,...,fear,joy,sadness,surprise,trust,negative,positive,brexit,roma,emilia
14752,14752,16468,16468,16560,giorgiomule,2019-02-07 15:40:00,laurea in lettere e filosofia,38306,759,370,...,0,0,0,0,2,0,4,False,False,False
14753,14753,16469,16469,16561,saveriocongedo,2019-02-07 15:40:00,laurea in lettere e filosofia,38306,759,370,...,0,0,0,0,0,0,0,False,False,False
14754,14754,16470,16470,16562,sabrimaggioni,2019-02-07 15:40:00,laurea in lettere e filosofia,38306,759,370,...,1,1,1,1,4,1,3,False,False,False
14755,14755,16471,16471,16563,benq_antonio,2019-02-07 15:40:00,laurea in lettere e filosofia,38306,759,370,...,1,0,1,0,1,3,0,False,False,False
14756,14756,16472,16472,16564,adri19510,2019-02-07 15:40:00,laurea in lettere e filosofia,38306,759,370,...,1,0,0,0,0,0,1,False,False,False
14757,14757,16473,16473,16565,nicolaporro,2019-02-07 15:40:00,laurea in lettere e filosofia,38306,759,370,...,2,0,3,2,0,4,1,False,False,False
14758,14758,16474,16474,16566,filomen30847137,2019-02-07 15:40:00,laurea in lettere e filosofia,38306,759,370,...,1,0,1,0,0,2,1,False,False,False
14759,14759,16475,16475,16567,lisadaca,2019-02-07 15:40:00,laurea in lettere e filosofia,38306,759,370,...,1,2,3,1,2,1,3,False,False,False
14760,14760,16476,16476,16568,adrianobusolin,2019-02-07 15:40:00,laurea in lettere e filosofia,38306,759,370,...,0,0,0,0,0,1,0,False,False,False
14761,14761,16477,16477,16569,"distefanotw,radiosavana",2019-02-07 15:40:00,laurea in lettere e filosofia,38306,759,370,...,0,0,0,0,0,0,0,False,False,False
14762,14762,16478,16478,16570,riccardofortin,2019-02-07 15:40:00,laurea in lettere e filosofia,38306,759,370,...,1,1,2,1,0,1,7,False,False,False
14763,14763,16479,16479,16571,nicolaporro,2019-02-07 15:40:00,laurea in lettere e filosofia,38306,759,370,...,0,0,0,0,0,0,0,False,False,False
14764,14764,16480,16480,16572,andreabonazzabz,2019-02-07 15:40:00,laurea in lettere e filosofia,38306,759,370,...,6,0,4,2,0,8,2,False,False,False
14765,14765,16481,16481,16573,marcorizzopc,2019-02-07 15:40:00,laurea in lettere e filosofia,38306,759,370,...,0,0,0,0,1,1,2,False,False,False
14766,14766,16482,16482,16574,chiodidonatella,Thu Feb 07 15:40:47 +0000 2019,laurea in lettere e filosofia,38053,752,370,...,1,1,2,0,1,2,1,False,True,False
14767,14767,16483,16483,16575,51fini,Thu Feb 07 15:40:47 +0000 2019,laurea in lettere e filosofia,38061,752,370,...,0,0,1,0,0,0,1,False,False,False
14768,14768,16484,16484,16576,federica989111,Thu Feb 07 15:40:47 +0000 2019,laurea in lettere e filosofia,38063,752,370,...,0,1,0,1,1,0,2,False,False,False
14769,14769,16485,16485,16577,mgdj56,Thu Feb 07 15:40:47 +0000 2019,laurea in lettere e filosofia,38085,752,370,...,2,0,0,0,0,0,2,False,False,False
14770,14770,16486,16486,16578,mgdj56,Thu Feb 07 15:40:47 +0000 2019,laurea in lettere e filosofia,38085,752,370,...,0,0,0,0,1,1,1,True,False,False
14771,14771,16487,16487,16579,imolaoggi,Thu Feb 07 15:40:47 +0000 2019,laurea in lettere e filosofia,38100,752,370,...,0,0,0,0,0,2,0,False,False,False
14772,14772,16488,16488,16580,adrywebber,Thu Feb 07 15:40:47 +0000 2019,laurea in lettere e filosofia,38104,752,370,...,2,1,0,1,1,0,1,False,True,False
14773,14773,16489,16489,16581,evelinaagliardi,Thu Feb 07 15:40:47 +0000 2019,laurea in lettere e filosofia,38111,752,370,...,0,0,0,0,0,0,0,True,False,False
14774,14774,16490,16490,16582,ilcastiga,Thu Feb 07 15:40:47 +0000 2019,laurea in lettere e filosofia,38188,753,371,...,0,0,1,0,1,1,1,False,False,False
14775,14775,16491,16491,16583,claudio_2022,Thu Feb 07 15:40:47 +0000 2019,laurea in lettere e filosofia,38190,753,371,...,0,0,0,1,1,1,4,False,False,False

In [36]:
result["hashtags"] = result["hashtags"].fillna("")

In [37]:
def find_brexit(x):
    if "brexit" in x:
        return (True)
    else:
        return(False)

In [38]:
result["brexit"] = result["hashtags"].apply(find_brexit)

In [39]:
result["brexit"].value_counts()

False    30460
True       543
Name: brexit, dtype: int64

In [40]:
brexit = result[result["brexit"] == True]

In [41]:
brexit["hashtags"].head()

45     brexit,ukelection,generalelection2019,exitpoll...
67     brexit,ukelection,generalelection2019,exitpoll...
69               generalelection2019,brexit,facciamorete
108    brexit,ukelection,generalelection2019,exitpoll...
109    brexit,ukelection,generalelection2019,exitpoll...
Name: hashtags, dtype: object

In [44]:
pos_brexit = brexit['positive'].mean()
neg_brexit = brexit['negative'].mean()
anger_brexit = brexit['anger'].mean()
anticipation_brexit = brexit['anticipation'].mean()
disgust_brexit = brexit['disgust'].mean()
fear_brexit = brexit['fear'].mean()
joy_brexit = brexit['joy'].mean()
sadness_brexit = brexit['sadness'].mean()
surprise_brexit = brexit['surprise'].mean()
trust_brexit = brexit['trust'].mean()

In [63]:
data =  {"positive" :[pos_brexit], "negative": [neg_brexit], "anger":[anger_brexit], 
                          "anticipation":[anticipation_brexit], "disgust_brexit": [disgust_brexit], 
                          "fear": [fear_brexit], "joy": [joy_brexit],"sadness":[sadness_brexit],
                          "surprise":[surprise_brexit],"trust":[trust_brexit]}
mpc_brexit = pd.DataFrame(data)

In [64]:
mpc_brexit

,positive,negative,anger,anticipation,disgust_brexit,fear,joy,sadness,surprise,trust
0,1.642726,1.219153,0.799263,1.022099,0.298343,0.64825,0.808471,1.014733,0.819521,0.946593

In [71]:
lower_bound = []
upper_bound = []
diff_mean = []
significa = []

clu0pos_mean = brexit.positive.mean()
clu0neg_mean = brexit.negative.mean()
clu0pos_std = brexit.positive.std()
clu0neg_std = brexit.negative.std()
numerosità = 543

err_st = math.sqrt((clu0pos_std**2/numerosità)+(clu0neg_std**2/numerosità))
alfa = 1.96
lower_bound.append(clu0pos_mean - clu0neg_mean - alfa*err_st)
upper_bound.append(clu0pos_mean - clu0neg_mean + alfa*err_st)
diff_mean.append(clu0pos_mean - clu0neg_mean)
if (clu0pos_mean - clu0neg_mean >= clu0pos_mean - clu0neg_mean + alfa*err_st) or (clu0pos_mean - clu0neg_mean <= clu0pos_mean - clu0neg_mean - alfa*err_st):
    significa.append("C'è differenza")
else: 
    significa.append("Non c'è differenza")

In [72]:
significa

["Non c'è differenza"]